name: webidl2js_dart_port
description: A sample command-line application.
version: 0.0.1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  string_unescape: ^2.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

